# 行列の取り扱い

## numpy

* 数値計算用のライブラリ
* ベクトル・行列の扱いが便利
* 高速な計算速度

## numpyのインポート
numpyモジュールをnpという名前でインポートすることが多い


In [1]:
import numpy as np

---
## ベクトル・行列の作成方法

### Array
np.arrayという関数に引数にリスト・タプルなどを与え、ベクトルを作成。  
\(1, 2, 3, 4 \)という1次元ベクトルxを作成する  

$$
x=
\begin{pmatrix}
0 & 1 & 2 & 3
\end{pmatrix}
$$

In [2]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

ここで、ベクトルを構成する各値の型はint型であることを注意する  
値の型はメンバ関数dtypeで確認できる

In [3]:
x.dtype

dtype('int32')

dtypeを変更したい場合は、メンバ関数astypeを使う。
例えばflot型に変更する場合は下記のようにする。

In [4]:
x = x.astype(float)
x.dtype

dtype('float64')

引数に二次元配列（リストのリスト）を与えれば行列ないしテンソルを定義できる。  
また、引数dtypeに要素の型を指定すると定義時に指定の型で行列が作成される。  
例えば、次のようなベクトルを作成する.

$$
{\bf A}=
\begin{bmatrix}
0 & 1 & 2 & 3 \\
4 & 5 & 6 & 7 \\
8 & 9 & 10 & 11 \\
12 & 13 & 14 & 15
 \end{bmatrix}
$$

In [5]:
A = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]],dtype=float)
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

各要素へのアクセスがリストと異なる。  
A\[i,j,…\]でi行目j列目…の要素にアクセスできる。スライスも使用可能である  
例えば行列Aの2行目以降最終行前までで最終列以外を取り出すと

In [6]:
A[1:-1,:-1]

array([[ 4.,  5.,  6.],
       [ 8.,  9., 10.]])

### csvファイルへの読み書き
#### 書き込み
行列やベクトルであれば、np.savetxt(filePath, numpy.array, delimiter=",")関数を使ってcsvファイルに出力できる.  
行列AをmatrixA.csvとして保存する場合、下記のとおりである

In [7]:
np.savetxt(".\matrixA.csv" , A, delimiter=",")

#### 読み込み
読み込む場合は、np.loadtxt(filePath,delimiter=",")を使う  
上で保存したmatrixAをA_csvとして読み込む

In [8]:
A_csv = np.loadtxt("./matrixA.csv", delimiter=",")
A_csv

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

### その他の配列作成方法
iからjまでをn個に分割したベクトルを作成する場合、
np.linspace(i,j,n)で作成できる  
例えば、0.0～1.0までを11個に分割する場合は下記のようになる  
$$
\begin{pmatrix}
0.0 & 0.1 & 0.2 & 0.4  & 0.5  & 0.6  & 0.7  & 0.8  & 0.9 & 1.0 
\end{pmatrix}
$$

In [9]:
np.linspace(0.0,1.0,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

n個の0で構成されるベクトルはnp.zeros(n)、n個の1で構成されるベクトルはnp.ones(n)で作成できる  
よって、10個の0で構成されるベクトル及び10個の1で構成される次のようになる  
$$
\begin{pmatrix}
0.0 & 0.0 & 0.0 & 0.0 & 0.0 & 0.0 & 0.0 & 0.0 & 0.0 & 0.0
\end{pmatrix}
$$
$$
\begin{pmatrix}
1.0 & 1.0 & 1.0 & 1.0 & 1.0 & 1.0 & 1.0 & 1.0 & 1.0 & 1.0
\end{pmatrix}
$$

In [10]:
np.zeros(10),np.ones(10)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

同様に単位ベクトルはnp.eye(n)で作成できる  


$$
{\bf I}
=
\begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
$$


上記、単位行列Iは次のとおりである

In [11]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

---

## 要素ごとの四則演算
上で作成したベクトルxの各要素に2を足すと

In [12]:
x + 2

array([3., 4., 5., 6.])

各要素を2倍したベクトルは

In [13]:
x * 2

array([2., 4., 6., 8.])

各要素を二乗したベクトルは

In [14]:
x ** 2.

array([ 1.,  4.,  9., 16.])

要素同士の掛け算をする  
例えば、Aとxの要素ごとの積は、xが行ベクトルであることを考慮すると次のようになる

In [15]:
A * x

array([[ 0.,  2.,  6., 12.],
       [ 4., 10., 18., 28.],
       [ 8., 18., 30., 44.],
       [12., 26., 42., 60.]])

行列やベクトルを変形させる場合、メンバ関数reshape(i,j,…)を使う。
i,jは行数、列数など各次元の要素数であり、成り行きで決まってほしいときは-1を使う。
例えばxを列ベクトルxtに変換する場合、次の通りである

In [16]:
xt = x.reshape(-1,1)
xt

array([[1.],
       [2.],
       [3.],
       [4.]])

Aとxtの各要素の積は次のようになる

In [17]:
A * xt

array([[ 0.,  1.,  2.,  3.],
       [ 8., 10., 12., 14.],
       [24., 27., 30., 33.],
       [48., 52., 56., 60.]])

---
## その他よく使うモジュール関数
### 内積

In [18]:
np.dot(A, x)

array([ 20.,  60., 100., 140.])

### 合計, 平均, 最大, 最小
行列Aに対して合計, 平均, 最大, 最小を計算する

In [19]:
np.sum(A), np.mean(A), np.max(A), np.min(A)

(120.0, 7.5, 15.0, 0.0)

それぞれ第２引数に処理したい軸を指定すると、指定した軸の外側に計算値が計算される  
例えば、各列ごとの処理の結果は行ベクトルとなる。
その行ベクトルを計算したい場合は引数0を取る

In [20]:
np.sum(A,0), np.mean(A,0), np.max(A,0), np.min(A,0)

(array([24., 28., 32., 36.]),
 array([6., 7., 8., 9.]),
 array([12., 13., 14., 15.]),
 array([0., 1., 2., 3.]))

同様の処理をメンバ関数でも実施できる

In [21]:
A.sum(0),A.mean(0),A.max(0),A.min(0)

(array([24., 28., 32., 36.]),
 array([6., 7., 8., 9.]),
 array([12., 13., 14., 15.]),
 array([0., 1., 2., 3.]))

#### 転置行列
メンバプロパティであるA.Tにより行列の転置が可能

In [22]:
A.T

array([[ 0.,  4.,  8., 12.],
       [ 1.,  5.,  9., 13.],
       [ 2.,  6., 10., 14.],
       [ 3.,  7., 11., 15.]])

尚、1次元ベクトルの転置は実施できないので、前述したreshape関数を使う

#### 数式関数あれこれ
* np.sqrt
* np.log10, np.log2, np.log
* np.sin, np.cos, np.tan
* np.asin, np.acos, np.atan
* np.rad2deg, np.deg2rad

In [23]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [24]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999])

In [25]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [26]:
np.arcsin(x/x.max())

array([0.25268026, 0.52359878, 0.84806208, 1.57079633])

In [27]:
np.rad2deg(np.array(np.pi))

180.0

---

## 連立方程式

下記の連立方程式を解く。

$$
 (A + I)  \cdot x = b 
$$

### 答えの準備
$(A + I) \cdot x$を計算しbを計算する

In [28]:
b = np.dot((A+I), x)
b

array([ 21.,  62., 103., 144.])

### solve

$(A + I) \cdot x_{unkown} = b$について、$x_{unkown}$を未知数として連立方程式を解く

In [29]:
np.linalg.solve((A+I),b)

array([1., 2., 3., 4.])

xが計算できている

###  直列バネの静的つり合い

下記のような１次元の直列バネの先端に荷重1N作用したときの、各節点の変位を求めよ。
尚、$k_0, k_1, k_2, k_3$はそれぞれ、1,2,3,4 \[N/mm\]とする


<img src="./spring01.png" width=60%>


まず、境界条件を考慮せずに、下図の状態を考える。

<img src="./spring02.png" width=55%>

各節点作用する力のつり合いは以下のように表される。

$$
\left\{
\begin{align*}
f_0 + k_0 (u_1 - u_0) \quad \qquad \qquad = 0 \\
f_1 +k_1 (u_2 - u_1) - k_0 ( u_1 -u_0) = 0 \\
f_2 + k_2 (u_3 - u_2) - k_1 ( u_2 -u_1) = 0 \\
f_3 + k_3 (u_4 - u_3) - k_2 ( u_3 -u_2) = 0 \\
f_4\quad \qquad \qquad - k_3 ( u_4 -u_3) = 0
\end{align*}
\right.
$$

これを、$Ku = f$の形に変形すると

$$
\begin{bmatrix}
k_0 & - k_0 & 0 & 0 & 0 \\
-k_0 &k_0 + k_1 & - k_1 & 0 & 0 \\
0 & - k_1 & k_1 + k_2 & -k_2 & 0 \\
0 & 0 & -k_2 & k_2 + k_3 & -k_3 \\
0 & 0 & 0 & -k_3 & k_3 
\end{bmatrix}
\begin{pmatrix}
u_0 \\ u_1 \\ u_2 \\u_3 \\ u_4
\end{pmatrix}
=
\begin{pmatrix}
f_0 \\ f_1 \\ f_2 \\f_3 \\ f_4
\end{pmatrix}
$$




#### 剛性マトリクス
$k_0, k_1, k_2, k_3$はそれぞれ、1,2,3,4 \[N/mm\]とし、
行列kをnumpyのarrayで定義する

In [30]:
k = np.array(
    [
        [ 1., -1.,   0,   0,   0],
        [-1.,  3., -2.,   0,   0],
        [  0, -2.,  5., -3.,   0],
        [  0,  0., -3.,  7., -4.],
        [  0,  0.,  0., -4.,  4.]
    ]
)
k

array([[ 1., -1.,  0.,  0.,  0.],
       [-1.,  3., -2.,  0.,  0.],
       [ 0., -2.,  5., -3.,  0.],
       [ 0.,  0., -3.,  7., -4.],
       [ 0.,  0.,  0., -4.,  4.]])

#### 境界条件の考慮
境界条件を適用する。
$u_0=0$であることを考慮すれば、kの１行目、１列目は計算不要となる。
行列kから１行１列目を除いたkbはスライスを用いると以下の通りである

In [31]:
kb=k[1:,1:]
kb

array([[ 3., -2.,  0.,  0.],
       [-2.,  5., -3.,  0.],
       [ 0., -3.,  7., -4.],
       [ 0.,  0., -4.,  4.]])

$f_1 = 0,\quad f_2=0,\quad f_3=0,\quad f_4=1.$であるので
外力ベクトルfは次のようになる

In [32]:
f = np.array([0,0,0,1.])
f

array([0., 0., 0., 1.])

#### 連立方程式を解く
よって連立方程式を解き、$u_1,\quad u_2,\quad u_3,\quad u_4$を計算すると

In [33]:
u1_4 = np.linalg.solve(kb,f)
u1_4

array([1.        , 1.5       , 1.83333333, 2.08333333])

#### 直列バネの変位量（検算）
合成バネとして考えたときk_allは下記の通りである。
$$
\frac{1}{k_{all}} = \frac{1}{k_{0}}+\frac{1}{k_{1}}+\frac{1}{k_{2}}+\frac{1}{k_{3}} \\
$$

この場合、端点$u_4$は下記のようにあらわさるので

$$
u_4 = \frac{f_4}{k_{all}}
$$

上の２つの式より
$$
u_4 = f_4 \cdot \left( \frac{1}{k_{0}}+\frac{1}{k_{1}}+\frac{1}{k_{2}}+\frac{1}{k_{3}} \right)
$$

具体的に計算すると、連立方程式の解と等しくなる

In [34]:
1.*( 1./1. + 1./2. + 1./3. + 1/4.)

2.083333333333333


#### 固定端反力の計算
固定端の反力$f_0$は

In [35]:
f_rec = np.dot(k[:,1:] , u1_4)
f_rec[0]

-0.999999999999999

おおよそ、-1.0であり静的なつり合いが計算できている

---
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img align="right" alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br /><br />
<div align="right"><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">python4engineer</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://github.com/TatsuyaKatayama/python4engineer" property="cc:attributionName" rel="cc:attributionURL">TatsuyaKatayama</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>. </div>
